### ISSUE TITLE
[bug] pe_kit doesn't like being suspended

### ISSUE THREAD

**Issue by GeoffWilliams** [GeoffWilliams/pe_kit#25]
When resuming a laptop, the monitor thread that updates the stop/start icon seems to be dead - uncaught exception?

**Comment by GeoffWilliams** [comment]
reproduced on mac:
```
 Exception in thread Thread-2:
WARNING:kivy:stderr: Exception in thread Thread-2:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
WARNING:kivy:stderr:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
WARNING:kivy:stderr:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "./main.py", line 717, in update_status
WARNING:kivy:stderr:   File "./main.py", line 717, in update_status
     self.daemon_status = self.daemon_alive()
WARNING:kivy:stderr:     self.daemon_status = self.daemon_alive()
   File "./main.py", line 842, in daemon_alive
WARNING:kivy:stderr:   File "./main.py", line 842, in daemon_alive
     version_info = self.cli.version()
WARNING:kivy:stderr:     version_info = self.cli.version()
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
     return self._result(self._get(url), json=True)
WARNING:kivy:stderr:     return self._result(self._get(url), json=True)
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
     return f(self, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, *args, **kwargs)
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/client.py", line 112, in _get
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/docker/client.py", line 112, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
WARNING:kivy:stderr:     return self.get(url, **self._set_request_timeout(kwargs))
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
     return self.request('GET', url, **kwargs)
WARNING:kivy:stderr:     return self.request('GET', url, **kwargs)
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
     resp = self.send(prep, **send_kwargs)
WARNING:kivy:stderr:     resp = self.send(prep, **send_kwargs)
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
     r = adapter.send(request, **kwargs)
WARNING:kivy:stderr:     r = adapter.send(request, **kwargs)
   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
WARNING:kivy:stderr:   File "/Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
     raise ReadTimeout(e, request=request)
WARNING:kivy:stderr:     raise ReadTimeout(e, request=request)
 ReadTimeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out. (read timeout=60)
WARNING:kivy:stderr: ReadTimeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out. (read timeout=60)
 
WARNING:kivy:stderr: 
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 65] No route to host
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 65] No route to host
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 65] No route to host
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 65] No route to host
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  [Errno 64] Host is down
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet http server error: Bad Gateway code: 502
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet http server error: Bad Gateway code: 502
DEBUG:__main__:toggle_docker_container clicked
```

**Comment by GeoffWilliams** [comment]
New output:
```
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/pe_kit_agent__/json HTTP/1.1" 200 None
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet stopped/unreachable at https://192.168.99.100:32882:  timed out
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet up and running :D
DEBUG:__main__:docker daemon ok :)
DEBUG:__main__:puppet up and running :D
DEBUG:__main__:docker daemon ok :)
```
